### ISSUE TITLE
gRPC slice of pointers

### ISSUE THREAD

**Issue by titpetric** [LastPossum/kamino#3]
Not an issue, rather just a discussion starter:

gRPC makes the decision to represent repeated structs (a slice) as `[]*T`; how does that decision impact cloning such slices? Each record within is asumed to be unique, however there's nothing in the language that prevents us from creating such a slice that reuses a large number of `*T`; 

Let's asume a trivial example, with some pointers:

[0xf00d, 0x1234, 0xf00d] - is the cloned slice expected to honor the references of [0] and [2]?

**Comment by LastPossum** [comment]
Thank you for highlighting it. The current implementation of kamino.Clone will preserve pointer equality if there is one in the source slice. This is implemented by using a [map of pointers in the cloning context.](https://github.com/LastPossum/kamino/blob/master/clone.go#L56).
